#!/bin/sh
# Lock screen if valid user found to be logged into DE

set -e

lock() {
    local _xsecurelock xinit_pid line user log tty ret=1

    _xsecurelock='XSS_SLEEP_LOCK_FD=1 XSECURELOCK_DISCARD_FIRST_KEYPRESS=0 XSECURELOCK_FONT="Ubuntu" /usr/bin/xsecurelock'

    xinit_pid=$(pidof xinit)
    [ -n $xinit_pid ] || return 1

    if (ps -p $xinit_pid > /dev/null 2>&1); then
        user=$(ps -p $xinit_pid -o user --no-header)
        log="/var/log/xsecurelock.$user"

        tty=$(ps -p $xinit_pid -o tty --no-header)
        if [ $(printf "$tty" | sed -e 's|^tty||') -eq $(fgconsole) ]; then
            [ -f "$log" ] && printf '\n' >> "$log"
            printf '%s\n' "$(date +'%F %T')" >> "$log"
            chmod 600 "$log"

            (su $user -c "sh -c '$_xsecurelock || kill -9 -1'" &) >> "$log" 2>&1
            ret=0
        fi
    fi

    return $ret
}

[ $(id -u) -ne 0 ] && exit 1
lock
