#!/bin/sh

# Set touchpad preferences
xinput set-prop 'SynPS/2 Synaptics TouchPad' 'libinput Tapping Enabled' 1
xinput set-prop 'SynPS/2 Synaptics TouchPad' 'libinput Natural Scrolling Enabled' 1
xinput set-prop 'SynPS/2 Synaptics TouchPad' 'libinput Disable While Typing Enabled' 0

# Keyboard preferences
setxkbmap gb
xset r rate 225 35

# Launch dbus session
[ -z "$DBUS_SESSION_BUS_ADDRESS" ] || eval "$(dbus-launch --sh-syntax --exit-with-session)"

# Launch pulseaudio daemon
start-pulseaudio-x11

# Set wallpaper
feh --bg-fill '/usr/share/backgrounds/xfce/xfce-stripes.png'

# Start redshift
redshift -t 6000:2700 -l ___:___

# Launch dwm with slstatus bar
slstatus &
dwm
